#!/usr/bin/env python

import sys
import fileinput
import datetime
import traceback

t0 = None

def process_line(line):
    global t0

    result = ''

    fields = line.split()
    tstamp = long(fields[0])
    tid = long(fields[1])
    evtstr = fields[2]

    if not t0:
        t0 = tstamp

    delta = tstamp - t0

    # Print the timestamp formatted in localtime.
    result += datetime.datetime.fromtimestamp(float(tstamp) / 1000000.0).strftime('%Y-%m-%d %H:%M:%S.%f')

    # Threadid
    result += " %7s" % ("[%d]" % (tid,),)

    result += " %7.3f" % (float(delta) / 1000.0)

    # Print the event name
    result += " %-32s" % (evtstr,)

    # Print the rest of the event
    result += ' '.join(fields[3:])

    return result

for line in fileinput.input():
    try:
        print process_line(line)
    except Exception as ex:
        print >> sys.stderr, "Exception processing: "
        print >> sys.stderr, line
        traceback.print_exc(file=sys.stderr)

